language: elixir

elixir:
  - '1.8.1'
otp_release:
  - '21.3'

cache:
  directories:
    - ~/.hex
    - ~/.mix
    - _build

install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

script:
  - mix test
  - mix dialyzer --halt-exit-status

# Leave only the .plt files in build
before_cache:
  - mix deps.clean --all --build
  - mix clean --build
